# Generated by Django 5.2 on 2025-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allrounder',
            fields=[
                ('player_id', models.CharField(primary_key=True, serialize=False)),
                ('player', models.CharField()),
                ('bowling_role', models.CharField(choices=[('LHS', 'left handed spinner'), ('RHS', 'right handed spinner'), ('LHP', 'left handed pacer'), ('RHP', 'right handed pacer')], default='unknown')),
                ('batting_role', models.CharField(choices=[('RH', 'Right hand'), ('LH', 'Left hand')], default='unknown')),
            ],
        ),
        migrations.CreateModel(
            name='batsmen',
            fields=[
                ('player_id', models.CharField(primary_key=True, serialize=False)),
                ('player', models.CharField()),
                ('is_wk', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('RH', 'Right hand'), ('LH', 'Left hand')], default='unknown')),
            ],
        ),
        migrations.CreateModel(
            name='bowlers',
            fields=[
                ('player_id', models.CharField(primary_key=True, serialize=False)),
                ('player', models.CharField()),
                ('role', models.CharField(choices=[('LHS', 'left handed spinner'), ('RHS', 'right handed spinner'), ('LHP', 'left handed pacer'), ('RHP', 'right handed pacer')], default='unknown')),
            ],
        ),
    ]
