# Generated by Django 5.2 on 2025-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrounder',
            name='team',
            field=models.CharField(choices=[('rcb', 'RCB'), ('csk', 'CSK'), ('rr', 'RR')], default='None'),
        ),
        migrations.AddField(
            model_name='batsmen',
            name='team',
            field=models.CharField(choices=[('rcb', 'RCB'), ('csk', 'CSK'), ('rr', 'RR')], default='None'),
        ),
        migrations.AddField(
            model_name='bowlers',
            name='team',
            field=models.CharField(choices=[('rcb', 'RCB'), ('csk', 'CSK'), ('rr', 'RR')], default='None'),
        ),
    ]
