# Generated by Django 5.2 on 2025-05-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allrounder_team_batsmen_team_bowlers_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.CharField(primary_key=True, serialize=False)),
                ('team1', models.CharField()),
                ('team2', models.CharField()),
                ('date', models.DateField()),
                ('venue', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('home_ground', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='allrounder',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams'),
        ),
        migrations.AlterField(
            model_name='batsmen',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams'),
        ),
        migrations.AlterField(
            model_name='bowlers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams'),
        ),
    ]
