# Generated by Django 5.2 on 2025-05-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_allrounder_team_alter_batsmen_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batsmen',
            name='team',
        ),
        migrations.RemoveField(
            model_name='bowlers',
            name='team',
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('player_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('bowling_role', models.CharField(choices=[('LHS', 'left handed spinner'), ('RHS', 'right handed spinner'), ('LHP', 'left handed pacer'), ('RHP', 'right handed pacer')], default='unknown')),
                ('batting_role', models.CharField(choices=[('RH', 'Right hand batsman'), ('LH', 'Left hand batsman')], default='unknown')),
                ('is_wk', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.teams')),
            ],
        ),
        migrations.DeleteModel(
            name='Allrounder',
        ),
        migrations.DeleteModel(
            name='batsmen',
        ),
        migrations.DeleteModel(
            name='bowlers',
        ),
    ]
