# Generated by Django 5.2 on 2025-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_batsmen_team_remove_bowlers_team_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
