# Generated by Django 5.2 on 2025-05-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_matches_team1_alter_matches_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='player_type',
            field=models.CharField(choices=[('allrounder', 'All Rounder'), ('batsmen', 'Batsmen'), ('bowler', 'Bowelr')], default='unknown'),
        ),
        migrations.CreateModel(
            name='allrounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_type', models.ForeignKey(limit_choices_to={'player_type': 'allrounder'}, on_delete=django.db.models.deletion.CASCADE, to='main.players')),
            ],
        ),
    ]
