# Generated by Django 5.2 on 2025-05-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_players_player_type_allrounder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allrounder',
        ),
    ]
